#! /usr/bin/env python

"""Launch the backup script.
"""

import sys
import argparse
import backup_script

def main(options):
    """Main program."""
    script = backup_script.BackupScript(options)
    script.run()
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="back up your current Linux OS",
             )
    parser.add_argument('-l', '--log', dest='log_level', default='WARNING',
        choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'],
        help='set logging level.  Default: WARNING')
    parser.add_argument('--noop', '--dry-run', '-n', default=False,
            action='store_true',
            help="don't do anything for real, useful with -lINFO or -lDEBUG")
    parser.add_argument('specfile')
    options = parser.parse_args()
    return options

if __name__ == "__main__":
    main(get_options())
